apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dot-5924
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dot-5924 
  name: dot-5924
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dot-5924 
